name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.PRODUCTION_ENV_SECRET }}" > .env
      - name: Sign in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t sonjuhyeon00/aicc-taskapp .
      - name: Push Docker Image
        run: docker push sonjuhyeon00/aicc-taskapp:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull sonjuhyeon00/aicc-taskapp:latest
      - name: Delete existing container
        run: docker rm -f reactContainer
      - name: Run container
        run: docker run -d -p 80:80 --name reactContainer sonjuhyeon00/aicc-taskapp
